version: "3.3"


services: 
  messages:
   container_name: rabbitmq
   image: rabbitmq:3-management
   tty: true
   hostname: rabbitmq
   ports:
    - 5672:5672
    - 15672:15672
   networks:
     - messaging
  user:
   container_name: user
   image: auctionista/user:1.2
   build:
    dockerfile: ./UserMicroService/Dockerfile
   ports: 
    - 7279:80
   networks:
     - messaging
   depends_on:   
    - messages
   restart: on-failure   
  
  auction:
   container_name: auction
   image: auctionista/auction:2.1
   build:
    dockerfile: ./AuctionMicroService/Dockerfile
   ports:
    - 7086:80
   networks:
    - messaging
   depends_on:
    - messages
   restart: on-failure

  authentication:
    container_name: authentication
    image: auctionista/authentication:1.0
    build:
     dockerfile: ./AuthenticationService/Dockerfile
    ports: 
     - 7292:80
    networks:
     - messaging
    depends_on: 
     - messages
    restart: on-failure

  bids:
    container_name: bids
    image: auctionista/bids:1.0
    build:
     dockerfile: ./BidMicroService/Dockerfile
    ports: 
     - 7206:80
    networks:
     - messaging
    depends_on: 
     - messages
    restart: on-failure

  email:
    container_name: email
    image: auctionista/email:1.0
    build:
     dockerfile: ./EmailService/Dockerfile
    ports: 
     - 7057:80
    networks:
     - messaging
    depends_on: 
     - messages
    restart: on-failure

  image:
    container_name: image
    image: auctionista/image:1.0
    build:
     dockerfile: ./ImageMicroservice/Dockerfile
    ports: 
     - 7141:80
    networks:
     - messaging
    depends_on: 
     - messages
    restart: on-failure

  postage:
    container_name: postage
    image: auctionista/postage:1.0
    build:
     dockerfile: ./PostageMicroService/Dockerfile
    ports: 
     - 7151:80
    networks:
     - messaging
    depends_on: 
     - messages
    restart: on-failure

  tags:
    container_name: tags
    image: auctionista/tags:1.0
    build:
     dockerfile: ./TagsMicroService/Dockerfile
    ports:
     - 7209:80
     
    networks:
     - messaging
    depends_on: 
     - messages
    restart: on-failure

  watchlist:
    container_name: watchlist
    image: auctionista/watchlist:1.0
    build:
     dockerfile: ./WatchlistMicroservice/Dockerfile
    ports: 
     - 7204:80
    networks:
     - messaging
    depends_on: 
     - messages
    restart: on-failure
  frontend:
    container_name: frontend
    image: auctionista/frontend:1.0
    build:
      context: ../../../frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
networks:
  messaging: 

volumes:
  rabbitmq: