name: Deploy prod
on:
  push:
    branches: [ Release-Sprint-4 ]  
  pull_request: 
    branches: [ Release-Sprint-4 ]  
jobs:
  build:
    name: Deploy to prod
    runs-on: ubuntu-latest
    steps: 
      - name: remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: "188.166.50.198"
          username: ${{secrets.SSH_USERNAME}}
          password: ${{secrets.SSH_PASSWORD}}
          port: ${{secrets.SSH_PORT}}
          script: |
            cd Auction
            git pull origin Release-Sprint-4
            cd backend/dotNet/MicroServices
            docker-compose build
            docker-compose up -d
