name: Deploy prod
on:
  push:
    branches: [ Release-Sprint-4 ]  
jobs:
  build:
    name: Deploy to prod
    runs-on: ubuntu-latest
    steps: 
      - name: remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: "188.166.50.198"
          username: ${{secrets.SSH_PASSWORD}}
          password: ${{secrets.SSH_PASSWORD}}
          port: ${{secrets.SSH_PORT}}
          script: |
            whereis nginx
