# This is a basic workflow to help you get started with Actions

name: Docker Builds

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
   
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     
      - uses: actions/checkout@v3
      - name: docker build auction
        run: |
          docker build ./backend/dotNet/MicroServices/AuctionMicroService -t auctionista/auction:2.1
        
      - name: Docker build authentication
        run: |
          docker build ./backend/dotNet/MicroServices/AuthenticationService auctionista/authentication:1.0
        
      - name: Docker build bid
        run: |
          docker build ./backend/dotNet/MicroServices/BidMicroService auctionista/bids:1.0
        
      - name: Docker build email
        run: |
          docker build ./backend/dotNet/MicroServices/EmailService auctionista/email:1.0
        
      - name: Docker build image
        run: |
          docker build ./backend/dotNet/MicroServices/ImageMicroService auctionista/image:1.0
        
      - name: Docker build postage
        run: |
          docker build ./backend/dotNet/MicroServices/PostageMicroService auctionista/postage:1.0
        
      - name: Docker build tags
        run: |
          docker build ./backend/dotNet/MicroServices/TagsMicroService auctionista/tags:1.0
        
      - name: Docker build user
        run: |
          docker build ./backend/dotNet/MicroServices/UserMicroService auctionista/user:1.2
        
      - name: Docker build watchlist
        run: |
          docker build ./backend/dotNet/MicroServices/WatchlistMicroService auctionista/watchlist:1.0
        
      - name: Docker build frontend
        run: |
          docker build ./frontend auctionista/frontend:1.3