name: ci

on:
  push:
    

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
       
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: build frontend
        uses: docker/build-push-action@v3
        with:
          image: auctionista/frontend
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
      

        name: build watchlist
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/watchlist
      -

        name: Build tags
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/tags
      -

        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/postage
      -

        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/image
      -

        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/email
      -

        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/bids
      -

        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/authentication
      -

        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/auction
      -

         name: Build and push
         uses: docker/build-push-action@v3
         with:
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/user
          
          
        
