name: Docker Image CI

on:
  push:
    branches: [Release-Sprint-4]
  pull_request: 
    branches: [Release-Sprint-4]
    

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      
      - uses: actions/checkout@v2
      - run: |
              docker build . --file backend/dotNet/MicroServices/AuctionMicroService/Dockerfile
        
