name: frontend test
on:
  pull_request:
    branches: [Release-Sprint-4]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          
      - name: "first test"
        uses: cypress-io/github-action@v2
          install: false
          wait-on: 'http://localhost:3000'
          browser: chrome
          working-directory: frontend
          spec: ./cypress/e2e/*