name: frontend test
on:
  pull_request:
    branches: [Relase-Sprint-4]
 start-v10:
   
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress tests
        uses: ./
        with:
          working-directory: frontend/cypress
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3000'
        
      
  
