name: frontend test
on:
  pull_request:
    branches: [Release-Sprint-4]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Cypress tests
        uses: cypress-io/github-action@v4
        with:
          working-directory: frontend
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3000'
          browser: chrome
          spec: ./CypressJS/component/Login.cy.js
          
      
  
